# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=150)),
                ('sort', models.CharField(max_length=20)),
                ('trackid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'slideshows',
                'ordering': ['sort'],
            },
        ),
    ]
